[project]
name = "basic-client"
version = "0.1.0"
description = "A basic client for a MCP server."
authors = [ {name = "Alexys"}, ]
requires-python = ">= 3.11"
dependencies = [
    "mcp[cli]>=1.5.0",
]
